name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Release, Debug]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup CMake
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

    - name: Build
      run: cmake --build build --config ${{ matrix.build_type }}

    - name: Test
      run: ./build/MyProject
      shell: bash
      working-directory: ${{ github.workspace }}

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: MyProject
        path: ./build/MyProject.exe
      if: matrix.os == 'windows-latest'
